# The staging deployment's inputs.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Committed deliberately. Nothing here is a credential — every secret is a
# Secret Manager *name*, resolved at run time by the service that needs it, and
# the passwords themselves are generated by Terraform and never written down.
#
# Before this file existed the four required variables were passed as -var flags
# on the command line, which meant the only record of what staging was built
# from was one shell's history. Rebuilding the stack from the configuration
# alone — which is the acceptance test — was not actually possible.

scentic_runtime_service_account = "scentic-staging-app@causal-hour-502018-c8.iam.gserviceaccount.com"
admin_email                     = "yair@scentic.com"

# Pinned to a tag, not :latest. A revision must be traceable to the commit it
# was built from.
gateway_image = "us-east1-docker.pkg.dev/causal-hour-502018-c8/scentic-agpl/gateway:d0b6784"

# The address signature invitations come from. Verified for the sending provider
# — SPF and DKIM on scentic.com — or the mail is delivered to spam when it is
# delivered at all.
smtp_from_address = "esign@scentic.com"

# Secret *names*, not values.
#
# These three are not optional in practice, despite defaulting to "". The
# gateway is created by `count = var.kimai_api_token_secret == "" ? 0 : 1`, so
# omitting the token name does not merely skip a feature — it plans the running
# gateway for destruction, and takes the signing-certificate IAM grants with it.
# They default to empty so the stack can be stood up in stages; leaving them
# empty afterwards is a different thing entirely.
kimai_api_token_secret                = "agpl-kimai-api-token"
signing_certificate_secret            = "agpl-signing-cert"
signing_certificate_passphrase_secret = "agpl-signing-passphrase"

# Our own build of the OpenSign backend, not the upstream image.
#
# Upstream's saveFile.js assigns to an undeclared `fileUrl` on the line after
# the upload succeeds, which in an ES module throws every time. Both published
# tags carry it, so there is no version to move to. deploy/Dockerfile.opensign-server
# adds the declaration and nothing else, and fails the build if the patch stops
# applying.
opensign_server_image = "us-east1-docker.pkg.dev/causal-hour-502018-c8/scentic-agpl/opensign-server:patched-1"
